/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gor.ta;

/**
 *
 * @author Nikzxs
 */
public class sewaForm extends javax.swing.JFrame {
    tblData booklist = new tblData();
    /**
     * Creates new form sewaForm
     */
    public sewaForm() {
        initComponents();
        jTable1.setModel(booklist.getTabel());
        
        Lpg.addItem("Badminton 1");
        Lpg.addItem("Badminton 2");
        Lpg.addItem("Futsal 1");
        Lpg.addItem("Futsal 2");
        Lpg.addItem("Futsal 3");
        Lpg.addItem("Futsal 4");
        
        for (int a=1; a<=31; a++){
        Tgl.addItem(""+a);
        }
        
        Bln.addItem("Januari");
        Bln.addItem("Februari");
        Bln.addItem("Maret");
        Bln.addItem("April");
        Bln.addItem("Mei");
        Bln.addItem("Juni");
        Bln.addItem("Juli");
        Bln.addItem("Agustus");
        Bln.addItem("September");
        Bln.addItem("Oktober");  
        Bln.addItem("November");
        Bln.addItem("Desember");
        
        for (int b=2020; b<=2024; b++){
        Thn.addItem(""+b);        
        } 
        
        for (int a=8; a<=21; a++){
        mulai.addItem(a+".00");
        }
        
        for (int a=9; a<=22; a++){
        selesai.addItem(a+".00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        book = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        Lpg = new javax.swing.JComboBox<>();
        Tgl = new javax.swing.JComboBox<>();
        Bln = new javax.swing.JComboBox<>();
        Thn = new javax.swing.JComboBox<>();
        mulai = new javax.swing.JComboBox<>();
        selesai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        hp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Aplikasi Sewa Lapangan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 11, -1, 14));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Lapangan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 500, 325));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Durasi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 122, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Nama Pemesan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 153, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("No. HP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 184, -1, -1));

        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 239, 67, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        Lpg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Lapangan" }));
        Lpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpgActionPerformed(evt);
            }
        });
        getContentPane().add(Lpg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 240, -1));

        Tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal" }));
        getContentPane().add(Tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, -1));

        Bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan" }));
        getContentPane().add(Bln, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, -1));

        Thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun" }));
        Thn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThnActionPerformed(evt);
            }
        });
        getContentPane().add(Thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, -1));

        mulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mulai" }));
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });
        getContentPane().add(mulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 119, -1, -1));

        selesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selesai" }));
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel7.setText("sampai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 150, 240, -1));
        getContentPane().add(hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 181, 240, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikzxs\\Desktop\\close-up-net-badminton-court-filtered-image-processed_1232-3526.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 880, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        booklist.getTabel().removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_hapusActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        String[] data = new String[6];
        data[0] = (""+Lpg.getSelectedItem());
        data[1]= (""+Tgl.getSelectedItem()+"-"+Bln.getSelectedItem()+"-"+Thn.getSelectedItem());
        data[2] = (""+mulai.getSelectedItem()+"-"+selesai.getSelectedItem());
        data[3] = nama.getText();
        data[4] = hp.getText();
        
        booklist.getTabel().addRow(data);
    }//GEN-LAST:event_bookActionPerformed

    private void ThnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThnActionPerformed

    private void LpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LpgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sewaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sewaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sewaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sewaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sewaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bln;
    private javax.swing.JComboBox<String> Lpg;
    private javax.swing.JComboBox<String> Tgl;
    private javax.swing.JComboBox<String> Thn;
    private javax.swing.JButton book;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> mulai;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> selesai;
    // End of variables declaration//GEN-END:variables
}
